packages:
  - client
  - admin

patchedDependencies:
  wouter@3.7.1: patches/wouter@3.7.1.patch

overrides:
  tailwindcss>nanoid: 3.3.7

allowBuilds:
  "@firebase/util": true
  "@tailwindcss/oxide": true
  esbuild: true
  protobufjs: true
